# User config
author: "Rachel Nacilla"
tagline: "Technologist | Agile Coach | People Leader"
description: "My name is Rachel. I use information technology to solve business problems and data to make the right decisions."
keywords: "Data Analyst, Business Analyst, Technology"
email: "rachelnacilla@gmail.com"
linkedin: "https://www.linkedin.com/in/rachelnacilla/"
twitter: "s"
github: "https://github.com/rachelnacilla"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed