# User config
author: "Rachel Nacilla"
tagline: "Technologist | Agile Coach | People Leader"
description: "Rachel Nacilla - Technologist and People Leader"
keywords: "Data Analyst, Business Analyst, Technology, People Leader, Product Manager, Scrum Master"
email: "rachelnacilla@gmail.com"
linkedin: "https://www.linkedin.com/in/rachelnacilla/"
twitter: "https://twitter.com/rachelintweets"
github: "https://github.com/rachelnacilla"


# Site config
baseurl: ""
url: "https://rachelnacilla.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed