# User config
author: "Rachel Nacilla"
tagline: "Technologist | Agile Coach | People Leader"
description: "My name is Rachel Nacilla and I am a data and business analyst. I use information technology to solve business problems and data to make the right decisions."
keywords: "Data Analyst, Business Analyst, Technology, People Leader"
email: "rachelnacilla@gmail.com"
linkedin: "https://www.linkedin.com/in/rachelnacilla/"
twitter: "https://twitter.com/rachelintweets"
github: "https://github.com/rachelnacilla"


# Site config
baseurl: ""
url: "https://rachelnacilla.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed